<script>
  // These bindings are generated by Wails on the first `wails dev` / `wails generate module`.
  // They expose the Go App methods (ui/app.go) to the frontend.
  import {
    Engines, TestSource, TestTarget, Assess, ExportAssessHTML, Plan, Run,
    SaveConfig, LoadConfig,
  } from "../wailsjs/go/main/App";
  import { EventsOn } from "../wailsjs/runtime/runtime";
  import { onMount } from "svelte";

  let sources = [];
  let targets = [];
  let src = { engine: "mssql", dsn: "" };
  let dst = { engine: "postgres", dsn: "" };
  let opts = { parallelism: 4, tables: [], stateFile: ".migrator-state.json" };

  let srcStatus = ""; // "", "ok", "fail"
  let dstStatus = "";
  let assessment = null;
  let report = null;
  let progress = {}; // table -> {rows, total, done, err}
  let phase = "";
  let busy = false;
  let error = "";
  let savedPath = "";

  onMount(async () => {
    const e = await Engines();
    sources = e.sources;
    targets = e.targets;
    EventsOn("progress", (p) => {
      if (p.Phase && !p.Table) phase = p.Phase;
      if (p.Table) {
        progress[p.Table] = { rows: p.RowsWritten, total: p.Total, done: p.Done, err: p.Err };
        progress = progress;
      }
    });
  });

  async function call(fn) {
    busy = true; error = "";
    try { return await fn(); }
    catch (e) { error = String(e); }
    finally { busy = false; }
  }

  const testSrc = () => call(async () => {
    srcStatus = ""; try { await TestSource(src); srcStatus = "ok"; } catch (e) { srcStatus = "fail"; throw e; }
  });
  const testDst = () => call(async () => {
    dstStatus = ""; try { await TestTarget(dst); dstStatus = "ok"; } catch (e) { dstStatus = "fail"; throw e; }
  });
  const doAssess = () => call(async () => { assessment = await Assess(src, dst); report = null; savedPath = ""; });
  const doExport = () => call(async () => { const p = await ExportAssessHTML(src, dst); if (p) savedPath = p; });
  const doPlan = () => call(async () => { report = await Plan(src, dst, opts); assessment = null; });
  const doRun = () => call(async () => { progress = {}; report = await Run(src, dst, opts); });

  let cfgMsg = "";
  const saveConfig = () => call(async () => {
    const p = await SaveConfig(src, dst, opts);
    cfgMsg = p ? "Đã lưu config: " + p : "";
  });
  const loadConfig = () => call(async () => {
    const c = await LoadConfig();
    if (!c) return;
    src = { engine: c.source.engine, dsn: c.source.dsn };
    dst = { engine: c.target.engine, dsn: c.target.dsn };
    opts = { ...opts, parallelism: c.migration.parallelism || 4, tables: c.migration.tables || [] };
    cfgMsg = "Đã nạp config.";
  });

  const badge = (s) => ["auto", "review", "unsupported"][s] || "auto";
  const label = (s) => ["Tự động", "Cần review", "Không hỗ trợ"][s] || "?";
  const dot = (st) => st === "ok" ? "🟢" : st === "fail" ? "🔴" : "";
</script>

<main>
  <div class="topbar">
    <h1>migrator — DB Migration</h1>
    <div class="cfgbtns">
      <button on:click={loadConfig} disabled={busy}>Nạp config</button>
      <button on:click={saveConfig} disabled={busy}>Lưu config</button>
    </div>
  </div>
  {#if cfgMsg}<p class="muted">{cfgMsg}</p>{/if}

  <section class="conn">
    <div class="card">
      <h3>Nguồn {dot(srcStatus)}</h3>
      <select bind:value={src.engine}>{#each sources as e}<option>{e}</option>{/each}</select>
      <input placeholder="DSN nguồn" bind:value={src.dsn} />
      <button on:click={testSrc} disabled={busy}>Test connection</button>
    </div>
    <div class="card">
      <h3>Đích {dot(dstStatus)}</h3>
      <select bind:value={dst.engine}>{#each targets as e}<option>{e}</option>{/each}</select>
      <input placeholder="DSN đích" bind:value={dst.dsn} />
      <button on:click={testDst} disabled={busy}>Test connection</button>
    </div>
  </section>

  <div class="actions">
    <button on:click={doAssess} disabled={busy}>Assess</button>
    <button on:click={doPlan} disabled={busy}>Plan (dry-run)</button>
    <button class="primary" on:click={doRun} disabled={busy}>Run</button>
    {#if busy}<span class="muted">đang chạy… {phase}</span>{/if}
  </div>

  {#if error}<p class="error">{error}</p>{/if}

  {#if assessment}
    <section>
      <div class="head">
        <h2>Assessment — {assessment.Summary.AutoPercent}% tự động</h2>
        <button on:click={doExport} disabled={busy}>Export HTML</button>
      </div>
      {#if savedPath}<p class="muted">Đã lưu: {savedPath}</p>{/if}
      <p class="muted">
        {assessment.Summary.TotalTables} bảng · {assessment.Summary.TotalColumns} cột ·
        {assessment.Summary.TotalViews} view · {assessment.Summary.TotalRoutines} routine ·
        ~{assessment.Summary.TotalRows} rows
      </p>
      {#each assessment.Tables as t}
        <h3>{t.Source} → {t.Target} <span class="badge {badge(t.Status)}">{label(t.Status)}</span></h3>
        <table>
          <tr><th>Cột nguồn</th><th>Cột đích</th><th>Kiểu nguồn</th><th>Kiểu đích</th><th>Trạng thái</th></tr>
          {#each t.Columns as c}
            <tr>
              <td>{c.Source}</td><td>{c.Target}</td>
              <td><code>{c.SourceType}</code></td><td><code>{c.TargetType}</code></td>
              <td><span class="badge {badge(c.Status)}">{label(c.Status)}</span></td>
            </tr>
          {/each}
        </table>
      {/each}
    </section>
  {/if}

  {#if Object.keys(progress).length}
    <section>
      <h2>Tiến độ</h2>
      {#each Object.entries(progress) as [table, p]}
        <div class="prog">
          <span>{table}</span>
          <div class="bar"><span style="width:{p.total ? Math.min(100, (p.rows / p.total) * 100) : (p.done ? 100 : 0)}%"></span></div>
          <span class="muted">{p.rows}{p.total ? " / " + p.total : ""} {p.done ? "✓" : ""}{p.err ? " ✗" : ""}</span>
        </div>
      {/each}
    </section>
  {/if}

  {#if report && report.DryRun}
    <section>
      <h2>Plan</h2>
      {#if report.DDL}<pre>{report.DDL.join("\n")}</pre>{/if}
      {#if report.Warnings}{#each report.Warnings as w}<p class="warn">⚠ {w.Object}: {w.Message}</p>{/each}{/if}
    </section>
  {/if}

  {#if report && !report.DryRun}
    <section>
      <h2>Kết quả — finalized: {report.Finalized ? "✓" : "✗"} · validated: {report.Validated ? "✓" : "✗"}</h2>
      <table>
        <tr><th>Bảng</th><th>Rows ghi</th><th>Rows nguồn</th><th>Trạng thái</th></tr>
        {#each report.Tables as t}
          <tr>
            <td>{t.Table}</td>
            <td>{t.RowsWritten}</td>
            <td>{t.SourceRows >= 0 ? t.SourceRows : "—"}</td>
            <td>
              {#if t.Skipped}<span class="muted">đã xong</span>
              {:else if t.Err}<span class="badge unsupported">{t.Err}</span>
              {:else}<span class="badge auto">OK</span>{/if}
            </td>
          </tr>
        {/each}
      </table>
    </section>
  {/if}
</main>
