<script>
  // These bindings are generated by Wails on the first `wails dev` / `wails generate module`.
  // They expose the Go App methods (ui/app.go) to the frontend.
  import { Engines, Assess, Plan, Run } from "../wailsjs/go/main/App";
  import { EventsOn } from "../wailsjs/runtime/runtime";
  import { onMount } from "svelte";

  let sources = [];
  let targets = [];
  let src = { engine: "mssql", dsn: "" };
  let dst = { engine: "postgres", dsn: "" };
  let opts = { parallelism: 4, tables: [], stateFile: ".migrator-state.json" };

  let assessment = null;
  let report = null;
  let progress = {}; // table -> {rows, total, done, err}
  let phase = "";
  let busy = false;
  let error = "";

  onMount(async () => {
    const e = await Engines();
    sources = e.sources;
    targets = e.targets;
    EventsOn("progress", (p) => {
      if (p.Phase && !p.Table) phase = p.Phase;
      if (p.Table) {
        progress[p.Table] = {
          rows: p.RowsWritten,
          total: p.Total,
          done: p.Done,
          err: p.Err,
        };
        progress = progress; // trigger reactivity
      }
    });
  });

  async function call(fn) {
    busy = true;
    error = "";
    try {
      return await fn();
    } catch (e) {
      error = String(e);
    } finally {
      busy = false;
    }
  }

  const doAssess = () => call(async () => { assessment = await Assess(src, dst); report = null; });
  const doPlan = () => call(async () => { report = await Plan(src, dst, opts); assessment = null; });
  const doRun = () => call(async () => { progress = {}; report = await Run(src, dst, opts); });

  const badge = (s) => ["auto", "review", "unsupported"][s] || "auto";
  const label = (s) => ["Tự động", "Cần review", "Không hỗ trợ"][s] || "?";
</script>

<main>
  <h1>migrator — DB Migration</h1>

  <section class="conn">
    <div class="card">
      <h3>Nguồn</h3>
      <select bind:value={src.engine}>{#each sources as e}<option>{e}</option>{/each}</select>
      <input placeholder="DSN nguồn" bind:value={src.dsn} />
    </div>
    <div class="card">
      <h3>Đích</h3>
      <select bind:value={dst.engine}>{#each targets as e}<option>{e}</option>{/each}</select>
      <input placeholder="DSN đích" bind:value={dst.dsn} />
    </div>
  </section>

  <div class="actions">
    <button on:click={doAssess} disabled={busy}>Assess</button>
    <button on:click={doPlan} disabled={busy}>Plan (dry-run)</button>
    <button class="primary" on:click={doRun} disabled={busy}>Run</button>
    {#if busy}<span class="muted">đang chạy… {phase}</span>{/if}
  </div>

  {#if error}<p class="error">{error}</p>{/if}

  {#if assessment}
    <section>
      <h2>Assessment — {assessment.Summary.AutoPercent}% tự động</h2>
      <p class="muted">
        {assessment.Summary.TotalTables} bảng · {assessment.Summary.TotalColumns} cột ·
        {assessment.Summary.TotalViews} view · {assessment.Summary.TotalRoutines} routine ·
        ~{assessment.Summary.TotalRows} rows
      </p>
      {#each assessment.Tables as t}
        <h3>{t.Source} → {t.Target} <span class="badge {badge(t.Status)}">{label(t.Status)}</span></h3>
        <table>
          <tr><th>Cột nguồn</th><th>Cột đích</th><th>Kiểu nguồn</th><th>Kiểu đích</th><th>Trạng thái</th></tr>
          {#each t.Columns as c}
            <tr>
              <td>{c.Source}</td><td>{c.Target}</td>
              <td><code>{c.SourceType}</code></td><td><code>{c.TargetType}</code></td>
              <td><span class="badge {badge(c.Status)}">{label(c.Status)}</span></td>
            </tr>
          {/each}
        </table>
      {/each}
    </section>
  {/if}

  {#if Object.keys(progress).length}
    <section>
      <h2>Tiến độ</h2>
      {#each Object.entries(progress) as [table, p]}
        <div class="prog">
          <span>{table}</span>
          <div class="bar"><span style="width:{p.total ? Math.min(100, (p.rows / p.total) * 100) : (p.done ? 100 : 0)}%"></span></div>
          <span class="muted">{p.rows}{p.total ? " / " + p.total : ""} {p.done ? "✓" : ""}{p.err ? " ✗" : ""}</span>
        </div>
      {/each}
    </section>
  {/if}

  {#if report}
    <section>
      <h2>{report.DryRun ? "Plan" : "Kết quả"}</h2>
      {#if report.DDL}<pre>{report.DDL.join("\n")}</pre>{/if}
      {#if report.Warnings}
        {#each report.Warnings as w}<p class="warn">⚠ {w.Object}: {w.Message}</p>{/each}
      {/if}
    </section>
  {/if}
</main>
